data = [
    {
        "source": "Reuters",
        "date": "2024-03-19T14:30Z",
        "reliability": "high",
        "data": "NVIDIA (NVDA) stock surges to new all-time high of $950.02, up 3.2% following announcement of new AI chip architecture. Market cap exceeds $2.3 trillion, making it the third most valuable company globally."
    },
    {
        "source": "Bloomberg",
        "date": "2024-03-19T13:45Z",
        "reliability": "high",
        "data": "NVIDIA's latest earnings report shows Q4 revenue of $22.1 billion, up 265% year-over-year. Data center revenue reaches $18.4 billion, driven by AI infrastructure demand."
    },
    {
        "source": "Wall Street Journal",
        "date": "2024-03-19T12:15Z",
        "reliability": "high",
        "data": "NVIDIA announces new partnerships with major cloud providers to expand AI infrastructure. Company expects continued strong growth in data center segment."
    },
    {
        "source": "Seeking Alpha",
        "date": "2024-03-19T11:30Z",
        "reliability": "medium",
        "data": "Analyst consensus raises NVIDIA price target to $1,100, citing strong AI demand and market leadership. Multiple firms upgrade stock rating to 'Strong Buy'."
    },
    {
        "source": "CNBC",
        "date": "2024-03-19T10:45Z",
        "reliability": "high",
        "data": "NVIDIA CEO Jensen Huang announces new AI initiatives at GTC conference. Company reveals next-generation GPU architecture with 2x performance improvement."
    },
    {
        "source": "Reddit r/stocks",
        "date": "2024-03-19T09:20Z",
        "reliability": "low",
        "data": "User speculation about potential NVIDIA stock split following recent price surge. Community discussion about long-term AI market growth potential."
    },
    {
        "source": "Financial Times",
        "date": "2024-03-19T08:30Z",
        "reliability": "high",
        "data": "NVIDIA expands manufacturing partnerships to meet growing AI chip demand. Company secures additional TSMC capacity for next-generation products."
    },
    {
        "source": "Twitter",
        "date": "2024-03-19T07:15Z",
        "reliability": "low",
        "data": "Multiple tech analysts predict NVIDIA could reach $1,200 per share by end of 2024. Discussion of AI boom and chip shortage impact."
    },
    {
        "source": "MarketWatch",
        "date": "2024-03-19T06:45Z",
        "reliability": "medium",
        "data": "NVIDIA's market dominance in AI chips faces increasing competition from AMD and Intel. Analysis suggests potential market share shifts in coming quarters."
    },
    {
        "source": "Investor's Business Daily",
        "date": "2024-03-19T05:30Z",
        "reliability": "medium",
        "data": "Technical analysis shows NVIDIA stock in strong uptrend with key support at $900. Volume indicators suggest continued institutional buying."
    },
    {'source': 'MarketWatch', 'date': '2024-03-19T15:00:00Z', 'reliability': 'low', 'data': "NVIDIA's revenue growth driven by AI chip sales"},
    {'source': 'Wall Street Journal', 'date': '2024-03-19T14:45:00Z', 'reliability': 'low', 'data': 'AMD announces AI chip intended to rival NVIDIA Blackwell'},
    {'source': "Barron's", 'date': '2024-03-19T14:30:00Z', 'reliability': 'high', 'data': 'CEO Jensen Huang comments on AI revolution'},
    {'source': 'X', 'date': '2024-03-19T14:15:00Z', 'reliability': 'high', 'data': 'NVDA to announce quarterly results tomorrow amid high expectations'},
    {'source': 'Financial Times', 'date': '2024-03-19T14:00:00Z', 'reliability': 'medium', 'data': 'AI chip demand continues to outstrip supply'},
    {'source': 'Business Insider', 'date': '2024-03-19T13:45:00Z', 'reliability': 'high', 'data': 'Retail volume spikes after unexpected earnings beat'},
    {'source': 'Substack', 'date': '2024-03-19T13:30:00Z', 'reliability': 'low', 'data': "TSMC confirms exclusive manufacturing deal for NVDA's new node"},
    {'source': 'Business Insider', 'date': '2024-03-19T13:15:00Z', 'reliability': 'low', 'data': 'AI chip demand continues to outstrip supply'},
    {'source': 'Seeking Alpha', 'date': '2024-03-19T13:00:00Z', 'reliability': 'low', 'data': 'Retail investors concerned over high valuation'},
    {'source': 'CNBC', 'date': '2024-03-19T12:45:00Z', 'reliability': 'medium', 'data': 'Retail investors concerned over high valuation'},
    {'source': 'Yahoo Finance', 'date': '2024-03-19T12:30:00Z', 'reliability': 'low', 'data': 'NVIDIA’s AI cloud service enters beta testing'},
    {'source': 'Wall Street Journal', 'date': '2024-03-19T12:15:00Z', 'reliability': 'medium', 'data': 'NVIDIA’s AI cloud service enters beta testing'},
    {'source': 'Reddit r/stocks', 'date': '2024-03-19T12:00:00Z', 'reliability': 'low', 'data': 'Expansion into robotics and autonomous vehicles'},
    {'source': 'Substack', 'date': '2024-03-19T11:45:00Z', 'reliability': 'high', 'data': 'Expansion into robotics and autonomous vehicles'},
    {'source': 'Substack', 'date': '2024-03-19T11:30:00Z', 'reliability': 'low', 'data': 'Partnerships with Tesla and Meta for GPU supply'},
    {'source': 'Substack', 'date': '2024-03-19T11:15:00Z', 'reliability': 'low', 'data': 'Major hedge fund increases NVDA position by 20%'},
    {'source': "Barron's", 'date': '2024-03-19T11:00:00Z', 'reliability': 'low', 'data': 'Speculation on stock split after price doubling'},
    {'source': 'Twitter', 'date': '2024-03-19T10:45:00Z', 'reliability': 'medium', 'data': 'Potential regulatory scrutiny over AI market dominance'},
    {'source': 'Reddit r/stocks', 'date': '2024-03-19T10:30:00Z', 'reliability': 'medium', 'data': 'AMD announces AI chip intended to rival NVIDIA Blackwell'},
    {'source': "Barron's", 'date': '2024-03-19T10:15:00Z', 'reliability': 'high', 'data': 'GPU export restrictions discussed in Congress'},
    {'source': 'Wall Street Journal', 'date': '2024-03-19T10:00:00Z', 'reliability': 'low', 'data': 'Institutional investor sentiment remains bullish'},
    {'source': 'Financial Times', 'date': '2024-03-19T09:45:00Z', 'reliability': 'high', 'data': 'Potential regulatory scrutiny over AI market dominance'},
    {'source': 'MarketWatch', 'date': '2024-03-19T09:30:00Z', 'reliability': 'medium', 'data': "NVIDIA's revenue growth driven by AI chip sales"},
    {'source': 'Reuters', 'date': '2024-03-19T09:15:00Z', 'reliability': 'medium', 'data': "NVIDIA's revenue growth driven by AI chip sales"},
    # {'source': 'Business Insider', 'date': '2024-03-19T09:00:00Z', 'reliability': 'low', 'data': 'Major hedge fund increases NVDA position by 20%'},
    # {'source': 'Reddit r/stocks', 'date': '2024-03-19T08:45:00Z', 'reliability': 'low', 'data': 'Speculation on stock split after price doubling'},
    # {'source': 'X', 'date': '2024-03-19T08:30:00Z', 'reliability': 'low', 'data': 'AMD announces AI chip intended to rival NVIDIA Blackwell'},
    # {'source': 'Wall Street Journal', 'date': '2024-03-19T08:15:00Z', 'reliability': 'high', 'data': "TSMC confirms exclusive manufacturing deal for NVDA's new node"},
    # {'source': 'Financial Times', 'date': '2024-03-19T08:00:00Z', 'reliability': 'high', 'data': 'Institutional investor sentiment remains bullish'},
    # {'source': 'Yahoo Finance', 'date': '2024-03-19T07:45:00Z', 'reliability': 'high', 'data': "Huang: AI is 'the new industrial revolution'"},
    # {'source': 'InvestorPlace', 'date': '2024-03-19T07:30:00Z', 'reliability': 'high', 'data': 'Institutional investor sentiment remains bullish'},
    # {'source': 'Substack', 'date': '2024-03-19T07:15:00Z', 'reliability': 'low', 'data': 'Retail investors concerned over high valuation'},
    # {'source': 'Reddit r/stocks', 'date': '2024-03-19T07:00:00Z', 'reliability': 'high', 'data': 'AI chip demand continues to outstrip supply'},
    # {'source': 'Bloomberg', 'date': '2024-03-19T06:45:00Z', 'reliability': 'low', 'data': 'GPU export restrictions discussed in Congress'},
    # {'source': 'CNBC', 'date': '2024-03-19T06:30:00Z', 'reliability': 'medium', 'data': 'NVIDIA’s AI cloud service enters beta testing'},
    # {'source': 'InvestorPlace', 'date': '2024-03-19T06:15:00Z', 'reliability': 'high', 'data': "Huang: AI is 'the new industrial revolution'"},
    # {'source': 'Seeking Alpha', 'date': '2024-03-19T06:00:00Z', 'reliability': 'medium', 'data': 'Retail volume spikes after unexpected earnings beat'},
    # {'source': 'Substack', 'date': '2024-03-19T05:45:00Z', 'reliability': 'high', 'data': 'Partnerships with Tesla and Meta for GPU supply'},
    # {'source': 'Reddit r/stocks', 'date': '2024-03-19T05:30:00Z', 'reliability': 'medium', 'data': 'Retail investors concerned over high valuation'},
    # {'source': 'Bloomberg', 'date': '2024-03-19T05:15:00Z', 'reliability': 'low', 'data': 'Speculation on stock split after price doubling'},
    # {'source': 'Bloomberg', 'date': '2024-03-19T05:00:00Z', 'reliability': 'high', 'data': 'NVIDIA’s AI cloud service enters beta testing'},
    # {'source': 'Bloomberg', 'date': '2024-03-19T04:45:00Z', 'reliability': 'medium', 'data': "TSMC confirms exclusive manufacturing deal for NVDA's new node"},
    # {'source': 'Seeking Alpha', 'date': '2024-03-19T04:30:00Z', 'reliability': 'high', 'data': 'NVDA to announce quarterly results tomorrow amid high expectations'},
    # {'source': "Barron's", 'date': '2024-03-19T04:15:00Z', 'reliability': 'low', 'data': 'AI chip demand continues to outstrip supply'},
    # {'source': 'Wall Street Journal', 'date': '2024-03-19T04:00:00Z', 'reliability': 'medium', 'data': 'Institutional investor sentiment remains bullish'},
    # {'source': "Barron's", 'date': '2024-03-19T03:45:00Z', 'reliability': 'low', 'data': 'NVIDIA’s AI cloud service enters beta testing'},
    # {'source': 'Wall Street Journal', 'date': '2024-03-19T03:30:00Z', 'reliability': 'low', 'data': 'Partnerships with Tesla and Meta for GPU supply'},
    # {'source': 'Bloomberg', 'date': '2024-03-19T03:15:00Z', 'reliability': 'high', 'data': "TSMC confirms exclusive manufacturing deal for NVDA's new node"},
    # {'source': 'Reddit r/stocks', 'date': '2024-03-19T03:00:00Z', 'reliability': 'high', 'data': "Huang: AI is 'the new industrial revolution'"},
    # {'source': 'Financial Times', 'date': '2024-03-19T02:45:00Z', 'reliability': 'high', 'data': 'Potential regulatory scrutiny over AI market dominance'},
    # {'source': 'Substack', 'date': '2024-03-19T02:30:00Z', 'reliability': 'low', 'data': "NVIDIA's revenue growth driven by AI chip sales"},
    # {'source': 'Wall Street Journal', 'date': '2024-03-19T02:15:00Z', 'reliability': 'medium', 'data': 'Partnerships with Tesla and Meta for GPU supply'},
    # {'source': 'Reuters', 'date': '2024-03-19T02:00:00Z', 'reliability': 'medium', 'data': 'Institutional investor sentiment remains bullish'},
    # {'source': 'InvestorPlace', 'date': '2024-03-19T01:45:00Z', 'reliability': 'high', 'data': 'NVDA to announce quarterly results tomorrow amid high expectations'},
    # {'source': 'X', 'date': '2024-03-19T01:30:00Z', 'reliability': 'low', 'data': 'Institutional investor sentiment remains bullish'},
    # {'source': 'Bloomberg', 'date': '2024-03-19T01:15:00Z', 'reliability': 'high', 'data': 'NVDA to announce quarterly results tomorrow amid high expectations'},
    # {'source': "Barron's", 'date': '2024-03-19T01:00:00Z', 'reliability': 'low', 'data': "NVIDIA's revenue growth driven by AI chip sales"},
    # {'source': 'InvestorPlace', 'date': '2024-03-19T00:45:00Z', 'reliability': 'low', 'data': 'New GPU launch with 3x power efficiency'},
    # {'source': 'Yahoo Finance', 'date': '2024-03-19T00:30:00Z', 'reliability': 'low', 'data': 'Major hedge fund increases NVDA position by 20%'},
    # {'source': 'Seeking Alpha', 'date': '2024-03-19T00:15:00Z', 'reliability': 'medium', 'data': 'NVDA to announce quarterly results tomorrow amid high expectations'},
    # {'source': "Barron's", 'date': '2024-03-19T00:00:00Z', 'reliability': 'high', 'data': 'Speculation on stock split after price doubling'},
    # {'source': 'InvestorPlace', 'date': '2024-03-18T23:45:00Z', 'reliability': 'low', 'data': 'Speculation on stock split after price doubling'},
    # {'source': 'Seeking Alpha', 'date': '2024-03-18T23:30:00Z', 'reliability': 'medium', 'data': 'Potential regulatory scrutiny over AI market dominance'},
    # {'source': 'Twitter', 'date': '2024-03-18T23:15:00Z', 'reliability': 'medium', 'data': 'Retail volume spikes after unexpected earnings beat'},
    # {'source': 'Substack', 'date': '2024-03-18T23:00:00Z', 'reliability': 'low', 'data': 'Major hedge fund increases NVDA position by 20%'},
    # {'source': 'InvestorPlace', 'date': '2024-03-18T22:45:00Z', 'reliability': 'medium', 'data': 'Expansion into robotics and autonomous vehicles'},
    # {'source': 'Business Insider', 'date': '2024-03-18T22:30:00Z', 'reliability': 'high', 'data': 'NVDA to announce quarterly results tomorrow amid high expectations'},
    # {'source': 'Business Insider', 'date': '2024-03-18T22:15:00Z', 'reliability': 'low', 'data': 'Retail volume spikes after unexpected earnings beat'},
    # {'source': 'Yahoo Finance', 'date': '2024-03-18T22:00:00Z', 'reliability': 'low', 'data': 'AMD announces AI chip intended to rival NVIDIA Blackwell'},
    # {'source': 'Business Insider', 'date': '2024-03-18T21:45:00Z', 'reliability': 'medium', 'data': 'AMD announces AI chip intended to rival NVIDIA Blackwell'},
    # {'source': 'X', 'date': '2024-03-18T21:30:00Z', 'reliability': 'low', 'data': 'CEO Jensen Huang comments on AI revolution'},
    # {'source': 'Reuters', 'date': '2024-03-18T21:15:00Z', 'reliability': 'low', 'data': 'Partnerships with Tesla and Meta for GPU supply'},
    # {'source': 'Seeking Alpha', 'date': '2024-03-18T21:00:00Z', 'reliability': 'high', 'data': 'GPU export restrictions discussed in Congress'},
    # {'source': 'Financial Times', 'date': '2024-03-18T20:45:00Z', 'reliability': 'high', 'data': 'Potential regulatory scrutiny over AI market dominance'},
    # {'source': 'Wall Street Journal', 'date': '2024-03-18T20:30:00Z', 'reliability': 'medium', 'data': 'Rumors of AI model training partnership with OpenAI'},
    # {'source': 'Yahoo Finance', 'date': '2024-03-18T20:15:00Z', 'reliability': 'high', 'data': 'NVIDIA’s AI cloud service enters beta testing'},
    # {'source': 'Yahoo Finance', 'date': '2024-03-18T20:00:00Z', 'reliability': 'medium', 'data': "TSMC confirms exclusive manufacturing deal for NVDA's new node"},
    # {'source': 'CNBC', 'date': '2024-03-18T19:45:00Z', 'reliability': 'low', 'data': 'NVDA to announce quarterly results tomorrow amid high expectations'},
    # {'source': 'Yahoo Finance', 'date': '2024-03-18T19:30:00Z', 'reliability': 'low', 'data': 'Institutional investor sentiment remains bullish'},
    # {'source': 'Financial Times', 'date': '2024-03-18T19:15:00Z', 'reliability': 'low', 'data': 'Major hedge fund increases NVDA position by 20%'},
    # {'source': 'Yahoo Finance', 'date': '2024-03-18T19:00:00Z', 'reliability': 'low', 'data': 'Institutional investor sentiment remains bullish'},
    # {'source': 'Reddit r/stocks', 'date': '2024-03-18T18:45:00Z', 'reliability': 'low', 'data': 'Analysts debate long-term sustainability of margins'},
    # {'source': 'Seeking Alpha', 'date': '2024-03-18T18:30:00Z', 'reliability': 'medium', 'data': 'AI chip demand continues to outstrip supply'},
    # {'source': 'Twitter', 'date': '2024-03-18T18:15:00Z', 'reliability': 'high', 'data': 'Rumors of AI model training partnership with OpenAI'},
    # {'source': 'X', 'date': '2024-03-18T18:00:00Z', 'reliability': 'low', 'data': 'AMD announces AI chip intended to rival NVIDIA Blackwell'},
    # {'source': 'Yahoo Finance', 'date': '2024-03-18T17:45:00Z', 'reliability': 'medium', 'data': 'Expansion into robotics and autonomous vehicles'},
    # {'source': 'Seeking Alpha', 'date': '2024-03-18T17:30:00Z', 'reliability': 'low', 'data': "TSMC confirms exclusive manufacturing deal for NVDA's new node"},
    # {'source': 'Financial Times', 'date': '2024-03-18T17:15:00Z', 'reliability': 'high', 'data': 'New GPU launch with 3x power efficiency'},
    # {'source': 'Reddit r/stocks', 'date': '2024-03-18T17:00:00Z', 'reliability': 'low', 'data': 'Retail investors concerned over high valuation'},
    # {'source': 'Reddit r/stocks', 'date': '2024-03-18T16:45:00Z', 'reliability': 'high', 'data': 'Partnerships with Tesla and Meta for GPU supply'},
    # {'source': 'X', 'date': '2024-03-18T16:30:00Z', 'reliability': 'medium', 'data': 'Partnerships with Tesla and Meta for GPU supply'},
    # {'source': 'Seeking Alpha', 'date': '2024-03-18T16:15:00Z', 'reliability': 'low', 'data': 'NVIDIA’s AI cloud service enters beta testing'},
    # {'source': 'Financial Times', 'date': '2024-03-18T16:00:00Z', 'reliability': 'high', 'data': 'Speculation on stock split after price doubling'},
    # {'source': 'CNBC', 'date': '2024-03-18T15:45:00Z', 'reliability': 'high', 'data': 'AI chip demand continues to outstrip supply'},
    # {'source': "Barron's", 'date': '2024-03-18T15:30:00Z', 'reliability': 'low', 'data': 'AMD announces AI chip intended to rival NVIDIA Blackwell'},
    # {'source': 'Twitter', 'date': '2024-03-18T15:15:00Z', 'reliability': 'medium', 'data': "Huang: AI is 'the new industrial revolution'"},
    # {'source': "Barron's", 'date': '2024-03-18T15:00:00Z', 'reliability': 'low', 'data': 'Rumors of AI model training partnership with OpenAI'},
    # {'source': 'Seeking Alpha', 'date': '2024-03-18T14:45:00Z', 'reliability': 'low', 'data': 'GPU export restrictions discussed in Congress'},
    # {'source': 'MarketWatch', 'date': '2024-03-18T14:30:00Z', 'reliability': 'low', 'data': 'Expansion into robotics and autonomous vehicles'},
    # {'source': 'InvestorPlace', 'date': '2024-03-18T14:15:00Z', 'reliability': 'medium', 'data': 'Partnerships with Tesla and Meta for GPU supply'},
]